#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v10
# autospec commit: 5905be9
#
Name     : R-ggsignif
Version  : 0.6.4
Release  : 3
URL      : https://cran.r-project.org/src/contrib/ggsignif_0.6.4.tar.gz
Source0  : https://cran.r-project.org/src/contrib/ggsignif_0.6.4.tar.gz
Summary  : Significance Brackets for 'ggplot2'
Group    : Development/Tools
License  : GPL-3.0
Requires: R-ggsignif-license = %{version}-%{release}
Requires: R-ggplot2
BuildRequires : R-ggplot2
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
This package provides an easy way to indicate if two groups are
    significantly different. Commonly this is shown by a bracket on top
    connecting the groups of interest which itself is annotated with the
    level of significance (NS, *, **, ***).  The package provides a single
    layer (geom_signif()) that takes the groups for comparison and the
    test (t.test(), wilcox.text() etc.) as arguments and adds the
    annotation to the plot.

%package license
Summary: license components for the R-ggsignif package.
Group: Default

%description license
license components for the R-ggsignif package.


%prep
%setup -q -n ggsignif

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1713890785

%install
export SOURCE_DATE_EPOCH=1713890785
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-ggsignif
cp %{_builddir}/ggsignif/LICENSE %{buildroot}/usr/share/package-licenses/R-ggsignif/8624bcdae55baeef00cd11d5dfcfa60f68710a02 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/ggsignif/CITATION
/usr/lib64/R/library/ggsignif/DESCRIPTION
/usr/lib64/R/library/ggsignif/INDEX
/usr/lib64/R/library/ggsignif/LICENSE
/usr/lib64/R/library/ggsignif/Meta/Rd.rds
/usr/lib64/R/library/ggsignif/Meta/features.rds
/usr/lib64/R/library/ggsignif/Meta/hsearch.rds
/usr/lib64/R/library/ggsignif/Meta/links.rds
/usr/lib64/R/library/ggsignif/Meta/nsInfo.rds
/usr/lib64/R/library/ggsignif/Meta/package.rds
/usr/lib64/R/library/ggsignif/Meta/vignette.rds
/usr/lib64/R/library/ggsignif/NAMESPACE
/usr/lib64/R/library/ggsignif/NEWS.md
/usr/lib64/R/library/ggsignif/R/ggsignif
/usr/lib64/R/library/ggsignif/R/ggsignif.rdb
/usr/lib64/R/library/ggsignif/R/ggsignif.rdx
/usr/lib64/R/library/ggsignif/WORDLIST
/usr/lib64/R/library/ggsignif/doc/index.html
/usr/lib64/R/library/ggsignif/doc/intro.R
/usr/lib64/R/library/ggsignif/doc/intro.Rmd
/usr/lib64/R/library/ggsignif/doc/intro.html
/usr/lib64/R/library/ggsignif/help/AnIndex
/usr/lib64/R/library/ggsignif/help/aliases.rds
/usr/lib64/R/library/ggsignif/help/figures/README-coord_flip-1.png
/usr/lib64/R/library/ggsignif/help/figures/README-dodge_comparison-1.png
/usr/lib64/R/library/ggsignif/help/figures/README-faceted_comparison-1.png
/usr/lib64/R/library/ggsignif/help/figures/README-orientation_argument-1.png
/usr/lib64/R/library/ggsignif/help/figures/README-simpe_comparison-1.png
/usr/lib64/R/library/ggsignif/help/figures/logo.svg
/usr/lib64/R/library/ggsignif/help/ggsignif.rdb
/usr/lib64/R/library/ggsignif/help/ggsignif.rdx
/usr/lib64/R/library/ggsignif/help/paths.rds
/usr/lib64/R/library/ggsignif/html/00Index.html
/usr/lib64/R/library/ggsignif/html/R.css
/usr/lib64/R/library/ggsignif/tests/testthat.R
/usr/lib64/R/library/ggsignif/tests/testthat/Rplots.pdf
/usr/lib64/R/library/ggsignif/tests/testthat/_snaps/errors.md
/usr/lib64/R/library/ggsignif/tests/testthat/_snaps/geom_signific_strict.md
/usr/lib64/R/library/ggsignif/tests/testthat/_snaps/snapshot_data.md
/usr/lib64/R/library/ggsignif/tests/testthat/_snaps/vdiffr/basic-plot-vdiffr.svg
/usr/lib64/R/library/ggsignif/tests/testthat/_snaps/vdiffr/flipping-aesthetics-works-vdiffr.svg
/usr/lib64/R/library/ggsignif/tests/testthat/_snaps/vdiffr/geom-works-the-same-way-as-stat-vdiffr.svg
/usr/lib64/R/library/ggsignif/tests/testthat/_snaps/vdiffr/geom-works-with-identity-vdiffr.svg
/usr/lib64/R/library/ggsignif/tests/testthat/test-errors.R
/usr/lib64/R/library/ggsignif/tests/testthat/test-geom_signific_basic.R
/usr/lib64/R/library/ggsignif/tests/testthat/test-geom_signific_strict.R
/usr/lib64/R/library/ggsignif/tests/testthat/test-parsing.R
/usr/lib64/R/library/ggsignif/tests/testthat/test-snapshot_data.R
/usr/lib64/R/library/ggsignif/tests/testthat/test-vdiffr.R

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-ggsignif/8624bcdae55baeef00cd11d5dfcfa60f68710a02
